_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 11
                - 49
                - 105
            "2":
                - 1
                - 11
                - 49
                - 105
            "3":
                - 13
                - 55
            "4": 3.10.16
            "5": 0.20.1
            "6": 4.52.4
            "12": 0.20.1
            "13": darwin-arm64
